// 按需全局引入 vant组件
import Vue from 'vue'
import { Button, Icon, Tabbar, TabbarItem, Toast, Empty, Col, Row, Popup, Step, Steps, Skeleton, Loading, Divider, Cell, CellGroup, IndexBar, IndexAnchor, Grid, GridItem, Collapse, CollapseItem } from 'vant'

Vue.use(Button)
Vue.use(Icon)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Toast)
Vue.use(Empty)
Vue.use(Col)
Vue.use(Row)
Vue.use(Popup)
Vue.use(Step)
Vue.use(Steps)
Vue.use(Skeleton)
Vue.use(Loading)
Vue.use(Divider)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(IndexBar)
Vue.use(IndexAnchor)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Collapse)
Vue.use(CollapseItem)
